server:
  port: 8765

spring:
  application:
    name: Consumer
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


eureka:
  client:
    service-url:
      defaultZone:  http://10.10.10.40:8761/eureka/
  instance:
    prefer-ip-address: true
